apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeops.fullname" . }}-configmap
  labels:
    app.kubernetes.io/name: {{ include "kubeops.name" . }}
    helm.sh/chart: {{ include "kubeops.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  kubeopsconfig.yaml: |
  {{- with .Values.kubeopsconfig }}
    {{- toYaml . | nindent 4 }}
  {{- end }}

